ttsx/cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
     url(r'^index/', views.index),

]

ttsx/tinymce/urls.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)
from django.conf.urls import url

from tinymce import views

urlpatterns = [
    url(r'^spellchecker/$', views.spell_check, name='tinymce-spellcheck'),
    url(r'^flatpages_link_list/$', views.flatpages_link_list, name='tinymce-linklist'),
    url(r'^compressor/$', views.compressor, name='tinymce-compressor'),
    url(r'^filebrowser/$', views.filebrowser, name='tinymce-filebrowser'),
]

ttsx/ttsx/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^goods/', include('goods.urls',namespace='goods')),
    url(r'^users/', include('users.urls',namespace='users')),
    url(r'^orders/', include('orders.urls',namespace='orders')),
    url(r'^cart/', include('cart.urls',namespace='cart')),

]

ttsx/users/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
     url(r'^index/$', views.index,name='index'),
     url(r'^login/$',views.login,name='login'),
     url(r'^register/$',views.register,name='register'),
     url(r'^register_handle/$',views.register_handle,name='register_handle'),
     url(r'^check_username_exist/$',views.check_username_exist,name='check_username_exist'),
     url(r'^login_handle/$',views.login_handle,name='login_handle'),
     url(r'^logout/$',views.logout,name='logout'),
     url(r'^user_center/$',views.user_center,name='user_center'),
     url(r'^user_order/$',views.user_order,name='user_order'),
     url(r'^user_site/$',views.user_site,name='user_site'),
     url(r'^update_address/$',views.update_address,name='update_address'),
     url(r'^my_send_mail/$',views.my_send_mail,name='my_send_mail'),
     url(r'^active_handle/(?P<token>.+)/$',views.active_handle,name='active_handle'),
]

ttsx/templates/common/base.html
{% load staticfiles %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-首页</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {% block header_js%} {% endblock header_js%}
</head>
<body>
{% block body %}  {% endblock body %}
	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

    {# 底部js #}
    {% block footer_js %}  {% endblock footer_js %}
</body>
</html>

ttsx/templates/common/status.html
<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
                {%  if request.session.username %}
				<div class="login_btn fl">
					欢迎您：<em>{{ request.session.username }}</em>
                    <span>|</span>
                    <a href="{% url 'users:logout' %}">登出</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'users:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'users:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="user_center_info.html">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="user_center_order.html">我的订单</a>
				</div>
			</div>
		</div>
	</div>