booktest2/book_app/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
	url(r'^$', index),
	#url(r'^(\d+)/$',detail),
	#url(r'^delete(\d+)$',delete),
	#url(r'^create$',create),
	#url(r'^area/(\d+)/$',area),
	#url(r'^get/$',get),
	#url(r'^post_index/$',post_index),
	#url(r'^post_b/$',post_b),
	#url(r'^redirect/$',redirect),
	#url(r'^ajax_index/$',ajax_index),
	#url(r'^json_data/$',json_data),
	#url(r'^cookie_set/$',cookie_set),
	#url(r'^cookie_get/$',cookie_get),
	#url(r'^test_cookie/',test_cookie),
	# url(r'^get_cookie/',get_cookie),
	# url(r'^delete_cookie/',delete_cookie),
	# url(r'^session_test/$',session_test),
	# url(r'^get_session/',get_session),
	# url(r'^session_test2/$',session_test2),
	# url(r'^session_del/',del_session),
	# url(r'^session_read/$',session_read),
	# url(r'^clear_session/$',clear_session),
	# url(r'^flush_session/$',flush_session),
	# url(r'^redis_session/$',redis_session),
	url(r'^book/$',book,name='book'),
	# url(r'^getcookie',getcookie),
	url(r'^session1/$',session1),
	url(r'^session2/$',session2),
	url(r'^session2_handle/$',session2_handle),
	url(r'^session3/$',session3),
	url(r'^static_test/$',static_test),
	url(r'^pic_upload/$', pic_upload),
	# 定义一个url 匹配规则，如果请求是127.0.0.1:8000/pic_handle/，那么就交给views 文件的pic_handle 函数处理
	url(r'^pic_handle/$', pic_handle),
	url(r'^show_pic/$',show_pic),
	url(r'^editor/$',editor),
	url(r'^show/$',show),
	url(r'^send_mail/$',send_mail),
	url(r'^verify_code/$',verify_code),
	url(r'^verify_show/$',verify_show),
	url(r'^verify_yz/$',verify_yz),
	url(r'^page(?P<pnum>\d*)/$',page_test),
	url(r'^cengjixuanze/$',cengjixuanze),
	url(r'^TuShu/$',TuShu),
	url(r'^RenWu(\d+)/$',RenWu),
	url(r'^areainfo_page(?P<pindex>\d*)/$',areainfo_page),
	url(r'^area1/$',area1),
	url(r'^area2/$',area2),
	url(r'^area3_(\d+)/$',area3)
 ]

booktest2/booktest2/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^admin/', include(admin.site.urls)),
	#url(r'^$',  index),
	#url(r'^(\d+)/$',detail),
	url(r'^', include('book_app.urls')),
]

booktest2/book_app/models.py
#coding:utf-8
from django.db import models
from tinymce.models import HTMLField

# Create your models here.
class BookInfo(models.Model):
	btitle = models.CharField(max_length=20)
	bpub_date = models.DateField()#发布日期
	bread = models.IntegerField(default=0)#阅读量
	bcomment = models.IntegerField(default=0)#评论量
	isDelete = models.BooleanField(default = False) #逻辑删除
	# books = BookInfoManager()
	def __str__(self):
		return self.btitle


class HeroInfo(models.Model):
	hname = models.CharField(max_length=20)#英雄姓名
	hgender = models.BooleanField(default=True)#英雄性别
	isDelete = models.BooleanField(default=False)#逻辑删除
	hcomment = models.CharField(max_length=200)#英雄描述信息
	hbook = models.ForeignKey('BookInfo')#英雄与图书表的关系为一对多，所以属性定义在英雄模型类中
	def __str__(self):
		return self.hname

	# def gongfu(self):
	# 	return self.hcomment
	# gongfu.admin_order_field='hcomment'
	# gongfu.short_description ='功夫'
	def book(self):
		if self.hbook is None:
			return ''
		return self.hbook.btitle
	book.short_description ='图书名称'
	book.admin_order_field = 'hbook'

class AreaInfo(models.Model):
	atitle = models.CharField(max_length=30)
	aParent = models.ForeignKey('self',null=True,blank=True)

#class BookInfoManager(models.Manager):
#	def get_queryset(self):
#		return super(BookInfoManager,self).get_queryset().filter(isDelete=False)


class PicTest(models.Model):
# 定义一个属性，他的作用就是定义我们提交图片的位置
	pic = models.ImageField(upload_to='book_app/')
	def __str__(self):
		return self.pic.name


class GoodsInfo(models.Model):
    gcontent = HTMLField()

booktest2/book_app/views.py
from django.shortcuts import render,redirect
from .models import *
from datetime import date
from django.http import HttpResponseRedirect
from django.http import  JsonResponse,HttpResponse
from django.conf import  settings
from django.core.mail import send_mail
from PIL import  Image,ImageDraw,ImageFont
from django.utils.six import  BytesIO
from django.core.paginator  import Paginator



# Create your views here.
def index(request):
  booklist = BookInfo.objects.all()
  #将图书列表传递到模板中，然后渲染模板
  print('生成相应对象,在执行return 给用户前，打印一句我是index')
  # raise Exception('自定义的异常')
  return render(request, 'book_app/index.html', {'Tem_booklist': booklist,"Tem_title":"图书列表"})

def detail(reqeust, bid):
    #根据图书编号对应图书
	book = BookInfo.objects.get(id=int(bid))
    #查找book图书中的所有英雄信息
	heros = book.heroinfo_set.all()
    #将图书信息传递到模板中，然后渲染模
	return render(reqeust, 'book_app/detail.html', {'book':book,'heros':heros})

def create(request):
	book = BookInfo()
	book.btitle ="流星蝴蝶剑"
	book.bpub_date = date(1996,12,23)
	book.save()
	return redirect('/')

def delete(request,id):
	book = BookInfo.books.get(pk=int(id))
	book.isDelete = True
	book.save()
	return redirect('/')


def area(request, aid):
	area = AreaInfo.objects.get(pk=int(aid))
	return render(request,'book_app/area.html',{'area':area})


def get(request):
	dict = request.GET
	a = dict.get('a')
	b = dict.get("b")
	c = dict.get('c')
	d = dict.get('d','4')
	e = dict.get('e')
	context = {'a':a,'b':b,'c':c,'d':d,'e':e}
	return render(request,'book_app/get_one.html',context)


def post_index(request):
	return render(request,'book_app/post_index.html')


def post_b(request):
    name = request.POST.get('name')
    # 指定一个获取密码的属性
    pwd = request.POST.get('pwd')
    # 指定一个获取性别的属性
    gender = request.POST.get('gender')
    # 指定一个获取爱好的属性
    hobbys = request.POST.get('hobby')
    context = {'T_name': name, 'T_pwd': pwd, 'T_gender': gender, 'T_hobbys': hobbys}
    return render(request, 'book_app/post_b.html', context)


# def redirect(request):
#     return HttpResponseRedirect("/get")


def ajax_index(request):
    return render(request,'book_app/ajax_1.html')


def json_data(request):
    booklist = BookInfo.objects.all()
    list = []
    for book in booklist:
        list.append({"name":book.btitle})
    jsondict = {"booklist":list}
    return  JsonResponse(jsondict)

def cookie_set(request):
    Response = HttpResponse("<h1>设置cookie,请查看相应包文头</h1>")
    Response.set_cookie("cookie2","ckvalue2")
    return Response

def cookie_get(request):
    if 'cookie2' in request.COOKIES:
        val = request.COOKIES['cookie2']
    else:
        val  = 'cookie 不存在'
    return HttpResponse(val)


def test_cookie(request):
    request.session.set_test_cookie()
    return HttpResponse("tsta")

def get_cookie(request):
    ret = request.session.test_cookie_worked()
    if ret:
        val = "验证成功"
        request.session.delete_test_cookie()
    else:
        val ="验证失败"
    return HttpResponse(val)

def delete_cookie(request):
    Response = HttpResponse('<h1>删除cookies,请查看相应报文</h1>')
    Response.delete_cookie('cookie2')
    # return HttpResponse(Response)
    return Response


def session_test(request):
    request.session['h1'] ='hello1'
    return HttpResponse('写session ok')


def get_session(request):
    sess = request.session.get('h1')
    return HttpResponse('sess')


def session_test2(request):
    request.session['h3'] ='helloworld3'
    return HttpResponse('ok')

def del_session(request):
    del request.session['h1']
    return HttpResponse("删除session ok")

def session_read(request):
    h1 = request.session.get('h4')
    return HttpResponse(h1)

def clear_session(request):
    request.session.clear()
    return HttpResponse("clear 删除所有的健的值")



def flush_session(request):
    request.session.flush()
    return HttpResponse('清除session数据，包括健以及值')


def redis_session(request):
    request.session['u1'] = 'tudou'
    return HttpResponse('it is ok')


# def getcookie(request):
#     response = HttpResponse("读取Cookie，数据如下：<br>")
#     if request.COOKIES.has_key()
#         response.write('<h1>' + request.COOKIES['cookie1'] + '</h1>')
#     return response


def book(request):
    booklist = BookInfo.objects.all()
    # booklist = []
    context = {"Tem_booklist":booklist,"Tem_title":"图书信息"}
    return render(request,'book_app/book.html',context)


def session1(request):
    uname = request.session.get('myname','未登陆')
    context = {'uname':uname}
    print('session1')
    return render(request,'book_app/session1.html',context)


def session2(request):
    print('session2')
    return render(request,'book_app/session2.html')


def session2_handle(request):
    print('session2_handler')
    uname = request.POST['uname']
    request.session['myname'] = uname
    return redirect('/book_app/session1/')


def session3(request):
    print('session3')
    del request.session['myname']
    return redirect('/book_app/session1/')

def static_test(request):
    return render(request,'book_app/static_file_2.html')

# 定义一个接受请求的函数，返回一个模板文件
def pic_upload(request):
    return render(request,'book_app/pic_upload.html')


def pic_handle(request):
    # 从request 的FILES 请求中，获取键为pic 的值，这个pic 值是我们提交表单中定义的
    #获取上传的图片数据流
    f1=request.FILES.get('pic')
    # 定义一个服务器上的文件上传地址：media/book_app/jingtai.jpg
    fname='%s/book_app/%s'%(settings.MEDIA_ROOT,f1.name)
    # 使用with 方式打开我们刚才定义的fname 文件，格式是wb，然后定义这个对象为pic

    with open(fname,'wb') as pic:
    # 遍历网络传输过来的文件数据流，
        #chunks()方法读取网络中的文件的数据流
        for c in f1.chunks():
        #将传输时候一段一段的数据存储到我们的fname 中
            pic.write(c)
    #刚才是将网络中的文件流，写到系统的磁盘上，并没有进行数据库的记录增加
    # 定义一个实例对象
    P1 = PicTest()
    # 给数据库中添加的数据记录为：book_app/jingtai.jpg
    P1.pic = 'book_app/%s'%f1.name
    # 对数据库对象操作，最后一步是保存数据
    P1.save()
    return HttpResponse('ok')


def show_pic(request):
    pic = PicTest.objects.all()
    context ={'Tem_pic':pic}
    return render(request,'book_app/show_pic.html',context)


def editor(request):
   return render(request,'book_app/editor.html')


def show(request):
    goods = GoodsInfo.objects.all()
    context = {'goods':goods}
    return render(request,'book_app/show.html',context)


def send_mail(request):
    msg='<a href="http://www.itcast.cn/subject/pythonzly/index.shtml" target="_blank">点击激活</a>'
    send_mail('注册激活','',settings.EMAIL_FROM,
              ['553895596@qq.com'],
              html_message=msg)
    return HttpResponse('ok')


def verify_code(request):
    import  random
    bgcolor = (random.randrange(20,100),random.randrange(20,100),255)
    width = 100
    height = 25
    im = Image.new('RGB',(width,height),bgcolor)
    draw = ImageDraw.Draw(im)
    for i in range(0,100):
        xy = (random.randrange(0,width),random.randrange(0,height))
        fill = (random.randrange(0,255),255,random.randrange(0,255))
        draw.point(xy,fill=fill)
    str1 ="abcdefghljkmnopqrstuvwxyzABCDEFGHLKJLMNOPRQSTUVWXYZ0123456789"
    str2 = ""
    for i in range(0,4):
        str2 += str1[random.randrange(0,len(str1))]
    font =ImageFont.truetype('FreeMono.ttf',23)
    fontcolor =(255,random.randrange(0,255),random.randrange(0,255))
    draw.text((5,2),str2[0],font=font,fill=fontcolor)
    draw.text((25,2),str2[1],font=font,fill=fontcolor)
    draw.text((50,2),str2[2],font=font,fill=fontcolor)
    draw.text((75,2),str2[3],font=font,fill=fontcolor)
    del draw
    request.session['verifycode'] = str2
    buf = BytesIO()
    im.save(buf,'png')
    return HttpResponse(buf.getvalue(),'image/png')

def verify_show(request):
    return render(request,'book_app/verify_show.html')

def verify_yz(request):
    yzm = request.POST.get('yzm')
    print('1--->',yzm)
    verifycode = request.session['verifycode']
    print('2--->',verifycode)
    res = HttpResponse('NO')
    if yzm == verifycode:
        res = HttpResponse('验证通过')
    # else:
        # response = HttpResponse('输入错误')
    return res


def page_test(request,pnum):
    hero = HeroInfo.objects.all()
    danye = Paginator(hero,5)
    if pnum =='':
        pnum = 1
    page_content = danye.page(int(pnum))
    page_num = danye.page_range
    context = {'Tem_title':'人物详情页','Tem_renwu':page_content,'Tem_pnum':page_num}
    return render(request,'book_app/fenye.html',context)

def cengjixuanze(request):
    return render(request,'book_app/cengjixuanzhe.html')


def TuShu(request):
    tushu = BookInfo.objects.all()
    tushu_list = []
    for ts in tushu:
        tushu_list.append([ts.id,ts.btitle])
    tushu_dict = {'Tudic':tushu_list}
    return JsonResponse(tushu_dict)


def RenWu(request,sid):
    renwu = HeroInfo.objects.filter(hbook_id = int(sid))
    renwu_list = []
    for rw in renwu:
        renwu_list.append({'heroname':rw.hname})
    renwu_dict = {'RenWuDic':renwu_list}
    return JsonResponse(renwu_dict)


def areainfo_page(request,pindex):
    list1 = AreaInfo.objects.filter(aParent__isnull=True)
    p =Paginator(list1,10)
    if pindex =='':
        pindex = 1
    pindex = int(pindex)
    plist = p.page_range
    #list2是获取某一页的所有内容
    list2 = p.page(pindex)
    context ={'list':list2,'plist':plist,'pindex':pindex}
    return render(request,'book_app/areainfo_page.html',context)


def area1(request):
    return render(request,'book_app/area1.html')

def area2(request):
    list1 = AreaInfo.objects.filter(aParent__isnull=True)
    list2 = []
    for area in list1:
        list2.append([area.id,area.atitle])
    area_dict = {'data':list2}
    return JsonResponse(area_dict)

def area3(request,pid):
    list3 = AreaInfo.objects.filter(aParent_id=pid)
    list4 = []
    for item in list3:
        list4.append({'id':item.id,'title':item.atitle})
    return JsonResponse({'data':list4})

booktest2/templates/book_app/ajax.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ajax功能展示</title>
    <!-- 需要在头部导入jquery文件  -->
    <script src="/static/js/jquery.js"></script>
</head>
<body>
    <input id="ajaxB" type="button" value="网页ajax局部刷新">
    <hr>
    <b>图书内容：</b>
    <ul id="blist"></ul>
</body>
</html>

booktest2/templates/book_app/ajax_data.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ajax功能展示</title>
    <!-- 需要在头部导入jquery文件-->
    <script src="/static/js/jquery.js"></script>
    <!-- ajax 功能测试-->
	<script>
	// 页面加载完再操作
	$(function () {
	    // 绑定ajaxB按钮点击事件
		$('#ajaxB').click(function () {
		    // 按钮出发的事件就是，发起一个ajax请求，
		    // 获取json_data函数返回的数据，jsondict表示请求回来的字典
			$.get('/json_data/', function (jsondict) {
			    // 定义一个变量名，他绑定后面的id为blist的ul标签
                $('#blist li').remove()
                booklist=$('#blist');
                // 遍历所有的jsondict.booklist的元素
                $.each(jsondict.booklist,function (i,book) {
                    // 获取每一个元素的name属性值(图书名称)，然后以列表的方式拼接
                    booklist.append('<li>'+book.name+'</li>');
                });
			});
		});
	});
	</script>
</head>
<body>
    <input id="ajaxB" type="button" value="网页微整形专家">
    <hr>
    <b>图书内容：</b>
    <ul id="blist"></ul>
</body>
</html>

booktest2/templates/book_app/ajax_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ajax功能展示</title>
    <!-- 需要在头部导入jquery文件-->
    <script src="/static/js/jquery.js"></script>
    <!-- ajax 功能测试-->
	<script>
	// 页面加载完再操作
	$(function () {
	    // 绑定ajaxB按钮点击事件
		$('#ajaxB').click(function () {
		    // 按钮出发的事件就是，发起一个ajax请求，
		    // 获取json_data函数返回的数据，jsondict表示请求回来的字典
			$.get('/json_data/', function (jsondict) {
                // 触发一个弹框
                alert("收到响应了吗？");
			});
		});
	});
	</script>
</head>
<body>
    <input id="ajaxB" type="button" value="网页微整形专家">
    <hr>
    <b>图书内容：</b>
    <ul id="blist"></ul>
</body>
</html>

booktest2/templates/book_app/area.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>地区</title>
</head>
<body>
当前地区：{{area.atitle}}
<hr/>
上级地区：{{area.aParent.atitle}}
<hr/>
下级地区：
<ul>
    {%for a in area.areainfo_set.all %}
    <li>{{a.atitle}}</li>
    {%endfor%}
</ul>

</body>
</html>

booktest2/templates/book_app/book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- 定义一个title的 变量名标签 Tem_title -->
    <title>{{Tem_title}}</title>
</head>
<body>
{%for book in Tem_booklist%}
{#    {% if book.id=2 %} #}
    {% if book.btitle|length > 4 %}
        <li> <a href="/renwu{{ book.id}}/" style="background-color: red"> {{ forloop.counter }}:
            {{ book.btitle }} </a>   ---默认时间格式为： {{book.bpub_date}} </li>

    {%  else %}
        <li> <a href="/renwu{{ book.id}}/" style="background-color: green"> {{ forloop.counter }}:
            {{ book.btitle }} </a>  ---默认时间格式为： {{book.bpub_date|date:"Y-m-j"}}  </li>
    {%  endif %}
{#    {% empty %}#}
{#    <p>施工重地,闲人免进</p>#}
{%  endfor %}
</body>
</html>

booktest2/templates/book_app/index.html
{% extends "base.html" %}
{%  block title %}

    {{ Tem_title }}

{%  endblock title %}

{% block body %}
    <a href="/book"> 图书信息</a>
    <ul>
        {%  for book in Tem_booklist  %}
        <li> <a href="/renwu{{ book.id }}"></a> {{ book.btitle }}</li>
        {%  endfor %}
	
    </ul>

{% endblock body %}

booktest2/templates/book_app/post_b.html
全部信息:{{ request.POST }}
<hr>
用户名：{{  T_name }}
<hr>
密码:{{  T_pwd }}
<hr>
性别:{{ T_gender }}
<hr>
爱好:{{ T_hobbys }}

booktest2/templates/book_app/post_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>post</title>
</head>
<body>
    <a href="/redirect/">redirect跳转</a>
    <form method="post" action="/post_b/">
        {% csrf_token %}
        姓名：  <input type="text" name="name"/><br>
        密码：<input type="password" name="pwd"/><br>
        性别：<input type="radio" name="gender" value="1"/>男&nbsp;
        <input type="radio" name="gender" value="0"/>女<br>
        爱好：<input type="checkbox" name="hobby" value="胸口碎大石"/>胸口碎大石
        <input type="checkbox" name="hobby" value="脚踩电灯炮"/>脚踩电灯炮
        <input type="checkbox" name="hobby" value="口吐火"/>口吐火<br>
        <input type="submit" value="提交"/>
    </form>

</body>
</html>

booktest2/templates/book_app/session1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>test session and cookies</title>
</head>
<body>
    hello,{{ uname }}
    <br>
    <a href="/book_app/session2/"> 登陆</a>
    <br>
    <a href="/book_app/session3/"> 退出 </a>
</body>
</html>

booktest2/templates/book_app/session2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form method="post" action="/book_app/session2_handle/">
        {% csrf_token %}
        <input type="text" name="uname">
        <input type="submit" name="登陆">


    </form>

</body>
</html>

booktest2/templates/book_app/show.html
<html>
<head>
    <title>展示富文本编辑器内容</title>
</head>
<body>
{% for g in goods %}
id:{{g.id}}
<hr>
{%autoescape off%}
{{g.gcontent}}
{%endautoescape%}
<hr>
{{g.gcontent|safe}}
{% endfor %}
</body>
</html>

booktest2/templates/book_app/show_pic.html
<html>
<head>
<title>显示上传的图片</title>
</head>
<body>
<p style="background-color: green ;font-size:20px;"> 图书展示</p>
{%  for pic in Tem_pic %}

<li style="background-color: aqua">
    <img src="/static/media/{{pic}}"/>
</li>
{%  endfor %}

</body>
</html>

booktest2/templates/book_app/static_file.html
{% extends "base.html" %}
{%  block title %} 静态图片 {% endblock %}
{% block body %}

<img src="/static/img/11.png"/>

{%endblock body%}

booktest2/templates/book_app/static_file_2.html
{% extends "base.html"%}

{%block title%}静态图片{%endblock title%}

{%block body%}
修改前：<img src="/static/img/1.jpg"/>
<hr>
动态配置：{%load static from staticfiles%}

<img src="{%static 'img/1.jpg' %}"/>

{%endblock body%}