ttsx/cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
     url(r'^index/', views.index),

]

ttsx/tinymce/urls.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)
from django.conf.urls import url

from tinymce import views

urlpatterns = [
    url(r'^spellchecker/$', views.spell_check, name='tinymce-spellcheck'),
    url(r'^flatpages_link_list/$', views.flatpages_link_list, name='tinymce-linklist'),
    url(r'^compressor/$', views.compressor, name='tinymce-compressor'),
    url(r'^filebrowser/$', views.filebrowser, name='tinymce-filebrowser'),
]

ttsx/ttsx/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^goods/', include('goods.urls',namespace='goods')),
    url(r'^users/', include('users.urls',namespace='users')),
    url(r'^orders/', include('orders.urls',namespace='orders')),
    url(r'^cart/', include('cart.urls',namespace='cart')),

]

ttsx/users/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
     url(r'^index/$', views.index,name='index'),
     url(r'^login/$',views.login,name='login'),
     url(r'^register/$',views.register,name='register'),
     url(r'^register_handle/$',views.register_handle,name='register_handle'),
     url(r'^check_username_exist/$',views.check_username_exist,name='check_username_exist'),
     url(r'^login_handle/$',views.login_handle,name='login_handle'),
     url(r'^logout/$',views.logout,name='logout'),
     url(r'^user_center/$',views.user_center,name='user_center'),
     url(r'^user_order/$',views.user_order,name='user_order'),
     url(r'^user_site/$',views.user_site,name='user_site'),
     url(r'^update_address/$',views.update_address,name='update_address'),
     url(r'^my_send_mail/$',views.my_send_mail,name='my_send_mail'),
     url(r'^active_handle/(?P<token>.+)/$',views.active_handle,name='active_handle'),
]

ttsx/users/models.py
from django.db import models
from db.BaseModel import *
from utils.wrappers import *
from utils.common import *

# Create your models here.
class UserManager(models.Manager):
    def get_userinfo_byname(self,username):
        try:
            return self.get(user_name = username)
        except User.DoesNotExist:
            return None

    #注册信息入库
    def register_userinfo_save(self,request):
        user_name = post(request,'user_name')
        user_pass = post(request,'user_pass1')
        user_mail = post(request,'user_mail')
        user = User()
        user.user_name = user_name
        user.user_pass = passwd_jiami(user_pass)
        user.user_mail = user_mail
        user.save()


    def update_user_address(self,request):
        user = User.objects.get_userinfo_byname(get_session(request,'username'))
        if not user:
            return
        user.user_recv = post(request,'user_recv')
        user.user_address = post(request,'user_address')
        user.user_code = post(request,'user_code')
        user.user_tele = post(request,'user_tele')
        user.save()


class User(BaseModel):
    user_name = models.CharField(max_length=20,verbose_name='用户名')
    user_pass = models.CharField(max_length=64,verbose_name='密码')
    user_mail = models.CharField(max_length=30,verbose_name='邮箱')
    user_active = models.BooleanField(default=False)
    user_recv = models.CharField(max_length=30,verbose_name='收件人')
    user_address = models.CharField(max_length=80,verbose_name='地址')
    user_code = models.CharField(max_length=6,verbose_name='邮编')
    user_tele = models.CharField(max_length=11,verbose_name='手机')

    objects = UserManager()


class UserCenterMenu(BaseModel):
    menu_name = models.CharField(max_length=30)
    menu_link = models.CharField(max_length=100)
    menu_flag = models.CharField(max_length=10)

ttsx/users/views.py
from django.shortcuts import render,HttpResponse,redirect
from .functions import  *
from django.core.urlresolvers import reverse
from .models import  *
from utils.wrappers import *
from django.http import  JsonResponse
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from django.conf import settings

# Create your views here.
def index(request):
    return HttpResponse('用户中心')


def login(request):
    return render(request,'users/login.html')


def register(request):
    message = get_info_messge(request)
    return render(request,'users/register.html',locals())


def register_handle(request):
    # print('res-->',check_register_params(request))
    if check_register_params(request):
        User.objects.register_userinfo_save(request)
        #调用发送邮件的函数
        send_active_mail(request)
        return redirect(reverse('users:login'))
    else:
        return redirect(reverse('users:register'))


def check_username_exist(request):
    #获取用户名,表单里面的name属性username
    username = get(request,'username')
    print('username is --->',username)
    #用户名存在
    if User.objects.get_userinfo_byname(username):
        return  JsonResponse({'ret':1})
    #用户名不存在
    else:
        return  JsonResponse({'ret':0})

def login_handle(request):
    #对登陆页面的输入数据进行校验
    # print('检查登陆参数--->', check_login_params(request))
    if check_login_params(request):
        #保持用户登陆状态
        keep_user_online(request)
        #保持用户名
        response = redirect(reverse('users:user_center'))
        remember_username(request,response)
        return  response
    #数据校验不成功重新跳转到登陆页面
    else:
        return redirect(reverse('users:login'))


@login_permission
@add_menu_info
def user_center(request):
    # menus = UserCenterMenu.objects.all()
    user = User.objects.get_userinfo_byname(get_session(request,'username'))
    return render(request,'users/user_center_info.html',locals())


@login_permission
@add_menu_info
def user_order(request):
    # menus = UserCenterMenu.objects.all()
    return render(request,'users/user_center_order.html',locals())


@login_permission
@add_menu_info
def user_site(request):
    # menus = UserCenterMenu.objects.all()
    user = User.objects.get_userinfo_byname(get_session(request, 'username'))
    return render(request,'users/user_center_site.html',locals())


def logout(request):
    del_session(request)
    return redirect(reverse('users:login'))


def update_address(request):
    #校验参数
    print('check user address params',check_user_address_params(request))
    if check_user_address_params(request):

        #如果通过，就更新入库
        # print('入库之前')
        User.objects.update_user_address(request)
        # print('入库之后')

    return redirect(reverse('users:user_site'))


def active_handle(request,token):
    # print('test bug test bug ')
    serializer = Serializer(settings.SECRET_KEY,3600)
    try:
        # print('1111111111111111111111111111111111111111111111111')
        user_id = serializer.loads(token).get("id")
        # 获得激活链接中的用户ID
        print('user_id is',user_id)
        user = User.objects.get(id = user_id)
        # print('user id and user',user_id,user)
        user.user_active = True
        # print('user active is ',user.user_active)
        user.save()
        # print('激活成功')
        # return HttpResponse('用户激活成功')
        # if user.user_active  == True:
        #成功激活跳转到登陆页面
        return redirect(reverse('users:login'))
    except:
        return HttpResponse('激活链接已经过期')


def  my_send_mail(request):

    return HttpResponse('发送邮件成功')

ttsx/templates/users/login.html
{% extends 'common/base.html' %}

{% load staticfiles %}

{% block body %}
	<div class="login_top clearfix">
		<a href="index.html" class="login_logo"><img src="{% static 'images/logo02.png' %}"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="#">立即注册</a>
				</div>
				<div class="form_input">
					<form method="post" action="{%  url 'users:login_handle' %}">
                        {% csrf_token %}
						<input type="text"  value = "{{ request.COOKIES.username }}" name="user_name" class="name_input" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="user_pass" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="user_remember">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock body %}


ttsx/templates/users/menu.html
{# 加载自定义过滤器 #}
{#{% load user_filters %}#}
{#<div class="left_menu_con clearfix">#}
{#    <h3>用户中心</h3>#}
{#    <ul>#}
{#        <li><a href="user_center_info.html">· 个人信息</a></li>#}
{#        <li><a href="user_center_order.html" class="active">· 全部订单</a></li>#}
{#        <li><a href="user_center_site.html">· 收货地址</a></li>#}
{#        {% for menu in flag|get_menu_list %}#}
{#            <li><a href="{{ menu.menu_link }}" class="{{ menu.menu_css }}">·{{ menu.menu_name }}</a></li>#}
{#        {% endfor %}#}
{#    </ul>#}
{#</div>#}

{# 装饰器 方式#}

<div class="left_menu_con clearfix">
    <h3>用户中心</h3>
    <ul>
        {% for menu in request.menus %}
            {% if menu.menu_flag == flag %}
                <li><a href="{{ menu.menu_link }}" class="active">· {{ menu.menu_name }}</a></li>
            {% else %}
                 <li><a href="{{ menu.menu_link }}" >· {{ menu.menu_name }}</a></li>
            {% endif %}
        {% endfor %}
    </ul>
</div>

{# 从数据库读取数据 #}
{#<div class="left_menu_con clearfix">#}
{#    <h3>用户中心</h3>#}
{#    <ul>#}
{#        {% for menu in menus %}#}
{#            {% if menu.menu_flag == flag %}#}
{#                <li><a href="{{ menu.menu_link }}" class="active"> .{{ menu.menu_name }}</a> </li>#}
{#            {% else %}#}
{#                <li><a href="{{ menu.menu_link }}">.{{ menu.menu_name }}</a></li>#}
{#            {% endif %}#}
{#        {% endfor %}#}
{#    </ul>#}
{#</div>#}

ttsx/templates/users/register.html
{% extends 'common/base.html' %}
{% load staticfiles %}
{% block header_js %}

	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"> </script>
	<script type="text/javascript" src="{% static 'js/register.js' %}"></script>

{% endblock header_js %}

{% block body %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="{% static 'images/logo02.png' %}"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>
i
		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="#">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form method="post"  action="{% url 'users:register_handle' %}">
					{% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
                         <span class="error_info" style="display: block">{{ message.user_name }}</span>

					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="user_pass1" id="pwd">
						<span class="error_tip">提示信息</span>
                         <span class="error_info" style="display: block">{{ message.user_pass }}</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="user_pass2" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="user_mail" id="email">
						<span class="error_tip">提示信息</span>
                        <span class="error_info" style="display: block">{{ message.user_mail }}</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>				
				</form>
			</div>

		</div>

	</div>
{% endblock body %}


ttsx/templates/users/user_center_info.html
{%  extends 'common/base.html' %}

{% load  staticfiles %}
{% block body %}
    {% include 'common/status.html' %}
	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="main_con clearfix">

        {%  include 'users/menu.html' with flag='info' %}

		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ user.user_recv |default:'未填写'}}</li>
							<li><span>联系方式：</span>{{ user.user_tele |default:'未填写'}}</li>
							<li><span>联系地址：</span>{{ user.user_address |default:'未填写'}}</li>
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
				<li>
					<a href="detail.html"><img src="{% static 'images/goods/goods003.jpg' %}"></a>
					<h4><a href="detail.html">大兴大棚草莓</a></h4>
					<div class="operate">
						<span class="prize">￥16.80</span>
						<span class="unit">16.80/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="{% static 'images/goods/goods004.jpg' %}"></a>
					<h4><a href="#">吐鲁番梨光杏</a></h4>
					<div class="operate">
						<span class="prize">￥5.50</span>
						<span class="unit">5.50/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="{% static 'images/goods/goods005.jpg' %}"></a>
					<h4><a href="#">黄肉桃</a></h4>
					<div class="operate">
						<span class="prize">￥10.00</span>
						<span class="unit">10.00/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="{% static 'images/goods/goods006.jpg' %}"></a>
					<h4><a href="#">进口西梅</a></h4>
					<div class="operate">
						<span class="prize">￥28.80</span>
						<span class="unit">28.8/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="{% static 'images/goods/goods007.jpg' %}"></a>
					<h4><a href="#">香梨</a></h4>
					<div class="operate">
						<span class="prize">￥6.45</span>
						<span class="unit">6.45/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
			</ul>
		</div>
		</div>
	</div>
{% endblock body %}

ttsx/templates/users/user_center_order.html
{% extends 'common/base.html' %}
{% load staticfiles %}
{%  block body %}
    {% include 'common/status.html' %}
	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="{%  static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="main_con clearfix">

        {%  include 'users/menu.html' with flag='order' %}

		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
				<ul class="order_list_th w978 clearfix">
					<li class="col01">2016-8-21 17:36:24</li>
					<li class="col02">订单号：56872934</li>
					<li class="col02 stress">未支付</li>		
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="{% static 'images/goods02.jpg' %}"></li>
									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>	
									<li class="col03">1</li>
									<li class="col04">11.80元</li>	
								</ul>
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="{% static 'images/goods02.jpg' %}"></li>
									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>	
									<li class="col03">1</li>
									<li class="col04">11.80元</li>	
								</ul>
							</td>
							<td width="15%">33.60元</td>
							<td width="15%">待付款</td>
							<td width="15%"><a href="#" class="oper_btn">去付款</a></td>
						</tr>
					</tbody>
				</table>
				
				<ul class="order_list_th w978 clearfix">
					<li class="col01">2016-8-21 17:36:24</li>
					<li class="col02">订单号：56872934</li>
					<li class="col02 stress">已支付</li>			
				</ul>
				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="{% static 'images/goods02.jpg' %}"></li>
									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>	
									<li class="col03">1</li>
									<li class="col04">11.80元</li>	
								</ul>
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="{% static 'images/goods02.jpg' %}"></li>
									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>	
									<li class="col03">1</li>
									<li class="col04">11.80元</li>	
								</ul>
							</td>
							<td width="15%">33.60元</td>
							<td width="15%">已付款</td>
							<td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
						</tr>
					</tbody>
				</table>

				<div class="pagenation">
					<a href="#"><上一页</a>
					<a href="#" class="active">1</a>
					<a href="#">2</a>
					<a href="#">3</a>
					<a href="#">4</a>
					<a href="#">5</a>
					<a href="#">下一页></a>
				</div>
		</div>
	</div>
{% endblock body %}


ttsx/templates/users/user_center_site.html
{% extends 'common/base.html' %}
{%  load staticfiles %}
{% block body %}
	{% include 'common/status.html' %}
	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="main_con clearfix">

	    {%  include 'users/menu.html' with flag='site' %}

		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						<dd>{{ user.user_address |default:'未填写' }} （{{ user.user_recv |default:'未填写'}} 收） {{ user.user_tele |default:'未填写'}}</dd>
					</dl>					
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form method="post" action="{%  url 'users:update_address' %}">
                        {% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="user_recv" value="{{ user.user_recv }}">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea name='user_address' class="site_area">{{ user.user_address }}</textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="user_code" value="{{ user.user_code }}">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="user_tele" {{ user.user_tele }}>
						</div>

						<input type="submit"  value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>
{% endblock body %}
