ttsx/cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
     url(r'^index/', views.index),

]

ttsx/goods/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
     url(r'^index/$', views.index,name='index'),
     url(r'^detail/$',views.detail,name='detail'),
]

ttsx/tinymce/urls.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)
from django.conf.urls import url

from tinymce import views

urlpatterns = [
    url(r'^spellchecker/$', views.spell_check, name='tinymce-spellcheck'),
    url(r'^flatpages_link_list/$', views.flatpages_link_list, name='tinymce-linklist'),
    url(r'^compressor/$', views.compressor, name='tinymce-compressor'),
    url(r'^filebrowser/$', views.filebrowser, name='tinymce-filebrowser'),
]

ttsx/ttsx/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^goods/', include('goods.urls',namespace='goods')),
    url(r'^users/', include('users.urls',namespace='users')),
    url(r'^orders/', include('orders.urls',namespace='orders')),
    url(r'^cart/', include('cart.urls',namespace='cart')),

]

ttsx/goods/models.py
from db.BaseModel import *
from tinymce.models import HTMLField
from django.db import models


class GoodsCategory(BaseModel):
    goods_name = models.CharField(max_length=50)
    goods_css = models.CharField(max_length=20)
    goods_image = models.ImageField()

class GoodsInfo(BaseModel):
    goods_name = models.CharField(max_length=50)
    goods_price = models.DecimalField(max_digits=10,decimal_places=2)
    goods_short = models.CharField(max_length=100)
    goods_desc = HTMLField()
    goods_unit = models.CharField(max_length=30)
    goods_status = models.BooleanField(default=True)
    goods_sale = models.IntegerField()
    goods_visit = models.IntegerField()
    goods_img = models.ImageField()
    goods_cag = models.ForeignKey(GoodsCategory)

#商品图片
class GoodsImages(BaseModel):
    #商品路径
    img_url = models.CharField(max_length=50)
    #所属商品
    img_goods = models.ForeignKey(GoodsInfo)


class ScrollAdv(BaseModel):
    ad_name = models.CharField(max_length=30)
    ad_link = models.CharField(max_length=100)
    ad_image = models.ImageField()
    ad_index = models.SmallIntegerField()


class ActivityAdv(BaseModel):
    ac_name = models.CharField(max_length=30)
    ac_link = models.CharField(max_length=100)
    ac_image = models.ImageField()
    ac_index = models.SmallIntegerField()

ttsx/goods/views.py
from django.shortcuts import render,HttpResponse
from .models import *
from utils.wrappers import *

# Create your views here.
def index(request):
    #最新添加的四个商品
    cags = GoodsCategory.objects.all()
    for cag in cags:
        cag.new = cag.goodsinfo_set.all().order_by('-id')[:4]
        cag.hot = cag.goodsinfo_set.all().order_by('-goods_visit')[:3]
    scradv = ScrollAdv.objects.all().order_by('ad_index')
    acvadv = ActivityAdv.objects.all().order_by('ac_index')

    return render(request,'goods/index.html',locals())

def detail(request):
    #通过商品id查询商品
    # 获取的id url地址上的id的值
    goods = GoodsInfo.objects.get(id = get(request,'id'))
    goods_new = GoodsInfo.objects.all().order_by('-id')[:2]
    return render(request,'goods/detail.html',locals())

ttsx/templates/goods/detail.html
{% extends 'common/base.html' %}
{%  load staticfiles %}
{% block header_js %}
<script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script>
    function update_total_price() {
        //　获得商品数量
        num = parseInt($('.num_show').val());
        // 获得商品单价
        price = parseInt($('.show_pirze').find('em').html());
        //更新总价
        total = num *price;
        $('.total').find('em').html(total.toFixed(2)+'元');
    }
    $(function (){
        $('.add').click(function () {
            num = parseInt($('.num_show').val());
            num += 1;
            //更新数量
            $('.num_show').val(num);
            update_total_price();
        })
        $('.minus').click(function () {
            num = parseInt($('.num_show').val());
            num -= 1;
            if (num < 1){
                num = 1;
            }
            $('.num_show').val(num);
            update_total_price();

        })

    })


    </script>

{%  endblock header_js %}
{% block body %}
    {% include 'common/status.html' %}

	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="images/logo.png"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="cart.html" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">1</div>
		</div>
	</div>

	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
					<li><a href="#" class="fruit">新鲜水果</a></li>
					<li><a href="#" class="seafood">海鲜水产</a></li>
					<li><a href="#" class="meet">猪牛羊肉</a></li>
					<li><a href="#" class="egg">禽类蛋品</a></li>
					<li><a href="#" class="vegetables">新鲜蔬菜</a></li>
					<li><a href="#" class="ice">速冻食品</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">新鲜水果</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="{% static goods.goods_img %}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ goods.goods_name }}</h3>
			<p>{{ goods.goods_short }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ goods.goods_price }}</em></span>
				<span class="show_unit">单  位：{{ goods.goods_unit }}</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr">+</a>
					<a href="javascript:;" class="minus fr">-</a>	
				</div> 
			</div>
			<div class="total">总价：<em>{{ goods.goods_price }}</em></div>
			<div class="operate_btn">
				<a href="javascript:;" class="buy_btn">立即购买</a>
				<a href="javascript:;" class="add_cart" id="add_cart">加入购物车</a>				
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>

				<ul>
                    {% for new in goods_new %}
					<li>
						<a href="{% url 'goods:detail'  %}?id={{ new.id }}"><img src="{% static new.goods_img %}"></a>
						<h4><a href="{% url 'goods:detail' %}?id={{ new.id }}">{{ new.goods_name }}</a></h4>
						<div class="prize">￥{{ new.goods_price }}</div>
					</li>
                    {%  endfor %}

				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd> {{ goods.goods_desc }} </dd>
				</dl>
			</div>

		</div>
	</div>
{% endblock body %}

    {% block footer_js %}
	<div class="add_jump"></div>

	<script type="text/javascript" src="js/jquery-1.12.2.js"></script>
	<script type="text/javascript">
		var $add_x = $('#add_cart').offset().top;
		var $add_y = $('#add_cart').offset().left;

		var $to_x = $('#show_count').offset().top;
		var $to_y = $('#show_count').offset().left;

		$(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
		$('#add_cart').click(function(){
			$(".add_jump").stop().animate({
				'left': $to_y+7,
				'top': $to_x+7},
				"fast", function() {
					$(".add_jump").fadeOut('fast',function(){
						$('#show_count').html(2);
					});

			});
		})
	</script>
{% endblock footer_js %}

ttsx/templates/goods/index.html
{% extends 'common/base.html' %}
{%  load staticfiles %}
{% block header_js %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock header_js %}
{%  block body %}
    {% include 'common/status.html' %}


	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="#" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">1</div>
		</div>
	</div>

	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">

            {% for cag in cags %}
			    <li><a href="#" class="{{ cag.goods_css }}">{{ cag.goods_name }}</a></li>
            {% endfor %}

		</ul>
		<div class="slide fl">
			<ul class="slide_pics">

                {%  for s in scradv %}
                    <li><a href="{{ s.ad_link }}"><img src="{% static s.ad_image %}" alt="{{ s.ad_name }}"></a></li>
                {% endfor %}

			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">

            {% for a in acvadv %}
			    <a href="{{ a.ac_link }}"><img src="{% static a.ac_image %}"></a>
            {% endfor %}

		</div>
	</div>
    {% for cag in cags %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model01">{{ cag.goods_name }}</h3>
			<div class="subtitle fl">
				<span>|</span>

                {% for goods in cag.hot %}
				    <a href="{% url 'goods:detail' %}?id={{ goods.id }}">{{ goods.goods_name }}</a>
                {% endfor %}

			</div>
			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{% static cag.goods_image %}"></div>
			<ul class="goods_list fl">
                {% for goods in cag.new %}
				<li>
					<h4><a href="{% url 'goods:detail' %}?id={{ goods.id }}">{{ goods.goods_name }}</a></h4>
					<a href="{% url 'goods:detail' %}?id={{ goods.id }}"><img src="{% static goods.goods_img %}"></a>
					<div class="prize">¥ {{ goods.goods_price }}</div>
				</li>
			    {% endfor %}
			</ul>
		</div>
	</div>
    {% endfor %}
{% endblock body %}

ttsx/templates/goods/list.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-商品列表</title>
	<link rel="stylesheet" type="text/css" href="css/reset.css">
	<link rel="stylesheet" type="text/css" href="css/main.css">
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_info fl">
					欢迎您：<em>张 山</em>
				</div>
				<div class="login_btn fl">
					<a href="login.html">登录</a>
					<span>|</span>
					<a href="register.html">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="user_center_info.html">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="user_center_order.html">我的订单</a>
				</div>
			</div>
		</div>		
	</div>

	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="images/logo.png"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="#" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl">1</div>
		</div>
	</div>

	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
					<li><a href="#" class="fruit">新鲜水果</a></li>
					<li><a href="#" class="seafood">海鲜水产</a></li>
					<li><a href="#" class="meet">猪牛羊肉</a></li>
					<li><a href="#" class="egg">禽类蛋品</a></li>
					<li><a href="#" class="vegetables">新鲜蔬菜</a></li>
					<li><a href="#" class="ice">速冻食品</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">新鲜水果</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
					<li>
						<a href="#"><img src="images/goods/goods001.jpg"></a>
						<h4><a href="#">进口柠檬</a></h4>
						<div class="prize">￥3.90</div>
					</li>
					<li>
						<a href="#"><img src="images/goods/goods002.jpg"></a>
						<h4><a href="#">玫瑰香葡萄</a></h4>
						<div class="prize">￥16.80</div>
					</li>
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="#" class="active">默认</a>
				<a href="#">价格</a>
				<a href="#">人气</a>
			</div>

			<ul class="goods_type_list clearfix">
				<li>
					<a href="detail.html"><img src="images/goods/goods003.jpg"></a>
					<h4><a href="detail.html">大兴大棚草莓</a></h4>
					<div class="operate">
						<span class="prize">￥16.80</span>
						<span class="unit">16.80/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="images/goods/goods004.jpg"></a>
					<h4><a href="#">吐鲁番梨光杏</a></h4>
					<div class="operate">
						<span class="prize">￥5.50</span>
						<span class="unit">5.50/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="images/goods/goods005.jpg"></a>
					<h4><a href="#">黄肉桃</a></h4>
					<div class="operate">
						<span class="prize">￥10.00</span>
						<span class="unit">10.00/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="images/goods/goods006.jpg"></a>
					<h4><a href="#">进口西梅</a></h4>
					<div class="operate">
						<span class="prize">￥28.80</span>
						<span class="unit">28.8/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="images/goods/goods007.jpg"></a>
					<h4><a href="#">香梨</a></h4>
					<div class="operate">
						<span class="prize">￥6.45</span>
						<span class="unit">6.45/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="images/goods/goods008.jpg"></a>
					<h4><a href="#">栗子</a></h4>
					<div class="operate">
						<span class="prize">￥9.50</span>
						<span class="unit">9.50/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="images/goods/goods009.jpg"></a>
					<h4><a href="#">海南香蕉</a></h4>
					<div class="operate">
						<span class="prize">￥3.30</span>
						<span class="unit">3.30/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="images/goods/goods010.jpg"></a>
					<h4><a href="#">青苹果</a></h4>
					<div class="operate">
						<span class="prize">￥5.00</span>
						<span class="unit">5.00/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="images/goods/goods011.jpg"></a>
					<h4><a href="#">山莓</a></h4>
					<div class="operate">
						<span class="prize">￥28.80</span>
						<span class="unit">28.8/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="images/goods/goods012.jpg"></a>
					<h4><a href="#">奇异果</a></h4>
					<div class="operate">
						<span class="prize">￥25.80</span>
						<span class="unit">25.8/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
				<li>
					<a href="#"><img src="images/goods/goods013.jpg"></a>
					<h4><a href="#">蜜桔</a></h4>
					<div class="operate">
						<span class="prize">￥4.80</span>
						<span class="unit">4.8/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
				<li>
					<a href="#"><img src="images/goods/goods014.jpg"></a>
					<h4><a href="#">脐橙</a></h4>
					<div class="operate">
						<span class="prize">￥3.50</span>
						<span class="unit">3.50/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
				<li>
					<a href="#"><img src="images/goods/goods001.jpg"></a>
					<h4><a href="#">进口柠檬</a></h4>
					<div class="operate">
						<span class="prize">￥3.90</span>
						<span class="unit">3.90/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
				<li>
					<a href="#"><img src="images/goods/goods002.jpg"></a>
					<h4><a href="#">玫瑰香葡萄</a></h4>
					<div class="operate">
						<span class="prize">￥16.80</span>
						<span class="unit">16.80/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
			</ul>

			<div class="pagenation">
				<a href="#"><上一页</a>
				<a href="#" class="active">1</a>
				<a href="#">2</a>
				<a href="#">3</a>
				<a href="#">4</a>
				<a href="#">5</a>
				<a href="#">下一页></a>
			</div>
		</div>
	</div>

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>